import numpy as np

class SMPCoreEngine:
    """
    SMP Core Physics Engine
    Anchors the fundamental parameters of the Steady-State Matrix Physics model.
    All calculations are validated against the 10^34 Pa Matrix integrity limit.
    """
    def __init__(self):
        # --- Fundamental Constants ---
        self.P_LIMIT = 1e34          # Pascal: Matrix integrity threshold
        self.SNAP_TEMP = 13.84       # Kelvin: The 'Snap' transition
        self.ETA_RIGID = 2.91e-12    # Pa·s: Viscosity in rigid phase (< 13.84K)
        self.A_PIONEER = 8.74e-10    # m/s²: Pioneer Anomaly acceleration
        
        # --- Derived Physical Constants ---
        self.C = 299792458           # m/s: Speed of light
        self.G = 6.67430e-11         # m³/kg·s²: Gravitational constant
        self.U_MATRIX = self.P_LIMIT # Matrix Energy Density (J/m³)

    def validate_matrix_state(self, current_temp):
        """Determines the physical state of the Matrix based on temperature."""
        is_rigid = current_temp < self.SNAP_TEMP
        viscosity = self.ETA_RIGID if is_rigid else 0.0
        state = "RIGID (Solidified)" if is_rigid else "SUPERFLUID (Liquid)"
        return {"state": state, "viscosity": viscosity}

    def calculate_pioneer_coupling(self, velocity=30000):
        """
        Calculates the friction coupling coefficient (k).
        Derived from Pioneer Anomaly data: k = a_p / v.
        """
        return self.A_PIONEER / velocity

    def calculate_thermal_gain(self, mass, velocity):
        """
        Calculates the thermal energy (Joules) generated by Pioneer Drag.
        Q = m * k * v^2
        """
        k = self.calculate_pioneer_coupling(velocity)
        return mass * k * (velocity**2)

    def calculate_mass_creation_rate(self, current_density):
        """
        Calculates the required mass creation (kg/s) to maintain steady-state density
        during expansion. Based on validated Expansion Efficiency: 2.62e-39 m^3/(kg·s).
        """
        expansion_efficiency = 2.62e-39 
        return current_density * expansion_efficiency

    def get_gas_pressure(self, temp, density, molar_mass=0.003002):
        """Calculates Helium-3 gas pressure (P = rho * R * T / M)."""
        R = 8.314
        return (density * R * temp) / molar_mass
